table dim_month
	lineageTag: cbee9d55-b443-4f8e-8bb3-66c48c751e91

	column month
		dataType: string
		lineageTag: 0f17fb07-bff4-49cf-b1dc-9c8c2d5d269d
		summarizeBy: none
		sourceColumn: month
		sortByColumn: month_start

	column month_start
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 4c13327d-6c69-445f-8d74-21124190ee20
		summarizeBy: none
		sourceColumn: month_start

		annotation UnderlyingDateTimeDataType = Date

	partition dim_month = m
		mode: import
		source =
				let
				    // Derived from the orders, never typed in. A calendar pinned to a range
				    // survives exactly until the seed moves; the healthcare report lost a year of
				    // cash to a (Blank) month that way, with every total still right.
				    Source = Csv.Document(File.Contents(DataPath & "\data\sales_lines.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Ordered = List.RemoveNulls(List.Transform(Table.Column(Promoted, "order_date"), each try Date.From(_) otherwise null)),
				    First = Date.StartOfMonth(List.Min(Ordered)),
				    Last = Date.StartOfMonth(List.Max(Ordered)),
				    Span = (Date.Year(Last) - Date.Year(First)) * 12 + Date.Month(Last) - Date.Month(First),
				    Months = List.Transform({0..Span}, each Date.AddMonths(First, _)),
				    ToTable = Table.FromList(Months, Splitter.SplitByNothing(), {"month_start"}),
				    Typed = Table.TransformColumnTypes(ToTable, {{"month_start", type date}}),
				    AddedLabel = Table.AddColumn(Typed, "month", each Date.ToText([month_start], "yyyy-MM"), type text),
				    Reordered = Table.ReorderColumns(AddedLabel, {"month", "month_start"})
				in
				    Reordered

